# .streamlit/secrets.toml

OPENAI_API_KEY-PRO_EDITION = 'sk-proj-rGKahnFw0LFvXsXdREz4T3BlbkFJgPJzsVTs8cDCQCTzNR2q'
OPENAI_API_KEY-MAX_EDITION = 'sk-proj-E2gJ75ngZzqDyoEnxYmFT3BlbkFJmEglo4dK1XyMXcodnHgx'
OPENAI_ORGANIZATION_ID = 'org-Ho7pjvc7rDjmJbm8eN62oeVY'
OPENAI_PROJECT_ID = 'proj_xzr5elB1B0iYtEKTE68N6vll'

[firebaseConfig]
apiKey = "AIzaSyA7Eb_qs-BoNmNK3EUcRF-1ebO2nGvSYw4"
authDomain = "alphapredict-ai.firebaseapp.com"
databaseURL = "https://alphapredict-ai-default-rtdb.firebaseio.com"
projectId = "alphapredict-ai"
storageBucket = "alphapredict-ai.appspot.com"
messagingSenderId = "189247031279"
appId = "1:189247031279:web:073fa7e3edff200a42981a"
measurementId = "G-7WYBCQB3CK"
